--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Savin1play140/CurrencyAPI
build-by-default: true
branches:
- main
projects:
  CurrencyAPI:
    path: ""
    libs:
      - src: Muqsit/simple-packet-handler
        version: 0.1.6
      - src: CortexPE/CortexPE/Commando
        version: 3.2.0
      
...