--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Savin1play140/CurrencyAPI
build-by-default: true
branches:
- main
projects:
  CurrencyAPI:
    path: ""
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.4
      - src: CortexPE/Commando/Commando
        version: 3.2.0
      
...